spring:
  application:
    name: chatBot
  datasource:
    url: jdbc:mysql://localhost:3306/chatBot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root  # 数据库用户名
    password: root  # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 104857600
      max-request-size: 104857600
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # 百炼大模型要去除v1
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
logging:
  level:
    org.springframework.ai: debug # AI对话的日志级别
    com.iteng.chatbot: debug # 本项目的日志级别
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true  # 开启驼峰命名转换
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志
#  global-config:
#    db-config:
#      id-type: auto  # 自增主键策略
#  mapper-locations: classpath*:/mapper/**/*.xml  # mapper xml文件位置
#  type-aliases-package: com.iteng.chatbot.entity  # 实体类包路径